# Generated by Django 4.0.6 on 2022-07-18 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=30)),
                ('autor', models.CharField(max_length=30)),
                ('fecha_lanzamiento', models.IntegerField()),
                ('idioma', models.CharField(max_length=15)),
                ('descripcion', models.CharField(max_length=500)),
                ('precio', models.IntegerField()),
            ],
        ),
    ]
