# Generated by Django 4.0.6 on 2022-07-22 02:00

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LibreriaApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=30)),
                ('subtitulo', models.CharField(max_length=50)),
                ('contenido', ckeditor.fields.RichTextField()),
                ('autor', models.CharField(max_length=30)),
                ('fecha_creacion', models.DateField()),
                ('imagen', models.ImageField(upload_to='')),
            ],
        ),
    ]
