# Generated by Django 4.0.6 on 2022-07-22 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LibreriaApp', '0002_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='imagen',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
