# Generated by Django 4.0.6 on 2022-07-22 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LibreriaApp', '0005_alter_post_fecha_creacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='imagen',
        ),
    ]
