# Generated by Django 4.0.6 on 2022-07-22 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LibreriaApp', '0006_remove_post_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='contenido',
        ),
    ]
