# Generated by Django 4.0.6 on 2022-07-25 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LibreriaApp', '0008_post_contenido'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Libro',
        ),
        migrations.AddField(
            model_name='post',
            name='imagen',
            field=models.ImageField(default=1, upload_to='media/'),
            preserve_default=False,
        ),
    ]
